pipeline:
  buid-docker: 
    image: docker:17.04.0-ce
    when:
      event: push
      branch: [master]
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login --username=registry --password=${REGISTRY_PASSWORD} registry.fsilva.me
      - docker build -t registry.fsilva.me/app:1.0.${DRONE_BUILD_NUMBER} app
      - docker build -t registry.fsilva.me/api:1.0.${DRONE_BUILD_NUMBER} api
      - docker push registry.fsilva.me/app:1.0.${DRONE_BUILD_NUMBER}
      - docker push registry.fsilva.me/api:1.0.${DRONE_BUILD_NUMBER}

  deploy-containers: 
    image: docker:17.04.0-ce
    when:
      event: push
      branch: [master]
    environment:
    - IMAGE_VERSION=1.0.${DRONE_BUILD_NUMBER}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker image prune -af
      - docker login --username=registry --password=$REGISTRY_PASSWORD registry.fsilva.me
      - docker stack deploy --with-registry-auth -c stack.yml web