version: '3'

services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo:/data/db
    command: mongod --smallfiles
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    placement:
        constraints:
          - node.labels.stack == app

  app:
    image: registry.fsilva.me/app:${IMAGE_VERSION}
    ports:
      - 3000:3000
    deploy:
      replicas: 1
  placement:
        constraints:
          - node.labels.stack == app

  api:
    image: registry.fsilva.me/api:${IMAGE_VERSION}
    deploy:
      replicas: 1
  placement:
        constraints:
          - node.labels.stack == app

volumes:
  mongo: